Refactor `harness` for support for Sub Tree Rendering
dojo/test-extras pull request #102
Opened 2018-01-25 15:14 UTC by agubler

**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

A ground up re-write of the `@dojo/test-extras#harness` for support of sub tree rendering. The new implementation supports a subset of the original API, approaching the requirements from a VDom perspective and using existing familiar APIs such as `w()`. Using `w()` is important as it is how widgets are written when used within Dojo 2.

```ts
// sets up the widget under test
const quxStub = stub();
const h = harness(() => w(WidgetUnderTest, { 
    foo: 'bar', 
    bar: true, 
    qux: quxStub 
}, [ 'child' ]);

// perform an assertion on the full `WidgetUnderTest` DNode structure against an expect 
// structure
h.expect(() => v('div', { 
    key: 'root', 
    classes: 'root', 
    foo: 'bar', 
    bar: 'true', 
    onclick: () => {} 
},  [ 
    v('span', { key: 'span' }, [ 'child' ])
]);

// perform an assertion on a partial of the `WidgetUnderTest` DNode structure against an
// expected structure using a selector to target the section of the DNode structure.
h.expectPartial('@span', () => v('span', { key: 'span' }, [ 'child' ]));

// trigger a function on one of the nodes in the DNode structure using a selector, 
// optionally passing arguments
h.trigger('.root', 'onclick');
assert.isTrue(quxStub.calledOnce);
```

As the harness (more specifically the widget under test) is not attached to the DOM, there some existing use-cases that will no longer be supported. We will look to provide additional functionality for the identified use-cases in subsequent updates, but initially it is important to concentrate on providing a clean, minimal, consistent API.

**This is a breaking changes and will require existing tests to be refactored.**

Resolves #101

2018-01-26 00:26 UTC, dylans requested changes
Lots of small tweaks and minor grammar nits.

2018-01-26 00:26 UTC, dylans commented on README.md
> + * Focused on testing Dojo 2 virtual dom structures
dom -> DOM

2018-01-26 00:26 UTC, dylans commented on README.md
> +* `renderFunction`: The a function that WNode for the widget under test
"The a function that WNode for the widget under test" ?

2018-01-26 00:26 UTC, dylans commented on README.md
> +* [`customComparators`](custom-comparators): Array of custom comparator descriptors. Each provides a comparator function to be used by during the comparison for `properties` located using a `selector
"to be used by during the comparison" -> to be used during the comparison

2018-01-26 00:26 UTC, dylans commented on README.md
> +* [`expect`](#harnessexpect): Performs an assertion against the entire virtual DOM from the widget under tests render.
"widget under tests render" ?

2018-01-26 00:26 UTC, dylans commented on README.md
> +* [`expectPartial`](#harnessexpectpartial): Performs an assertion against a section of virtual DOM from the widget under tests render.
"widget under tests render"?

2018-01-26 00:26 UTC, dylans commented on README.md
> +The harness also supports `tsx` usage as show below. The rest of the README examples in will use the programmatic `w()` API, there are more examples of `tsx` in the [unit tests](./blob/master/tests/u
"examples in will use the programmatic " ?

2018-01-26 00:26 UTC, dylans commented on README.md
> +The `renderFunction` is lazily executed so can include additional logic to manipulate the widget's `properties` and `children` between assertions.
"so can include additional logic" missing a word?

2018-01-26 00:26 UTC, dylans commented on README.md
> +For all assertions using the returned `harness` API will now only test identified `id` properties using the `comparator` instead of the standard equality.
assertions using -> assertions, using

2018-01-26 00:26 UTC, dylans commented on README.md
> +The `harness` APIs commonly support a concept of css style selectors to target nodes within the virtual DOM for assertions and operations. The full list of supported selectors be found [here](https:/
css -> CSS

2018-01-26 00:26 UTC, dylans commented on README.md
> +The `harness` APIs commonly support a concept of css style selectors to target nodes within the virtual DOM for assertions and operations. The full list of supported selectors be found [here](https:/
The full list of supported selectors be found [here](https://github.com/fb55/css-select#supported-selectors) -> Review the [full list of supported selectors](https://github.com/fb55/css-select#supported-selectors) for more information.

2018-01-26 00:26 UTC, dylans commented on README.md
> +* The `@` sigil is supported as shorthand for targeting a node's `key` property
sigil -> symbol

2018-01-26 00:26 UTC, dylans commented on README.md
> +* The `classes` property is used instead of `class` when using the stand shorthand `.` for targeting classes
stand shorthand -> standard shorthand?

2018-01-26 00:26 UTC, dylans commented on README.md
> +If the actual render output and expected render output are different an exception is thrown with a structured visualization indicating all differences with `(A)` (the actual value) and `(E)` (the exp
different an exception -> different, an exception

2018-01-26 00:26 UTC, dylans commented on README.md
> +### harness.expectPartial
should things like this harness.expectPartial be `harness.expectPartial` ? (If not, ignore)

2018-01-26 00:26 UTC, dylans commented on README.md
> +* `expectedRenderFunction`: The a function that returns the expected DNode structure of the queried node
The a function -> The function

2018-01-26 00:26 UTC, dylans commented on README.md
> +Example Usage:
Example usage:

2018-01-26 00:26 UTC, dylans commented on README.md
> +API
Is this API line supposed to be here?

2018-01-26 00:26 UTC, dylans commented on README.md
> +## How Do I Contribute?
How do I contribute?

2018-01-26 00:26 UTC, dylans commented on README.md
> +### Code Style
Code style

2018-01-26 00:26 UTC, dylans commented on README.md
> +- [How Do I Contribute?](#how-do-i-contribute)
How do I contribute?

2018-01-26 00:26 UTC, dylans commented on README.md
> +    - [Code Style](#code-style)
Code style

2018-01-26 00:26 UTC, dylans commented on README.md
> +  - [Custom Comparators](#custom-comparators)
Custom comparators

2018-01-26 00:26 UTC, dylans commented on README.md
> +    - [Setup Installation](#installation)
Setup installation

2018-01-26 00:26 UTC, dylans commented on README.md
> +- [Licensing Information](#licensing-information)
Licensing information

2018-01-26 00:46 UTC, agubler commented
@dylans addressed everything except the capitalisation comments, as discussed having capitalised headings is consistent with other package readmes.

2018-01-26 01:00 UTC, dylans approved these changes

2018-01-30 16:07 UTC, tomdye approved these changes

2018-01-30 23:01 UTC, merged