Add stub widget mapping functionality
dojo/test-extras pull request #16
Opened 2017-04-13 10:07 UTC by kitsonk

**Type:** feature

The following has been addressed in the PR:

* [X] There is a related issue
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [X] Unit or Functional tests are included in the PR

**Description:**

This PR provides the ability for someone harnessing widgets for test to specify specific widget stubs to substitute for sub widgets of the harnessed widget.  For a full description of the functionality, [see the updated README](https://github.com/dojo/test-extras/tree/feature-sub-widget-stubbing#sub-widget-stubbing).

Resolves #14

2017-04-13 19:34 UTC, bitpshr approved these changes
Looks good, the API seems nice enough. When we convert existing components (specifically Select and ComboBox) we may identify additional needs.

2017-04-13 22:05 UTC, dylans requested changes
a few typos

2017-04-13 22:05 UTC, dylans commented on README.md
> +is a iterable that provides a map of sub widget constructors to substitute.  There is a thrid optional argument which is an
an iterable

2017-04-13 22:05 UTC, dylans commented on README.md
> +is a iterable that provides a map of sub widget constructors to substitute.  There is a thrid optional argument which is an
thrid -> third

2017-04-13 22:05 UTC, dylans commented on README.md
> +`HTMLElement` to append the root of the harness to.  By default, it appends its root as the last child of `document.body`.
"to append the root of the harness to" -> to which the root of the harness is appended?

2017-04-13 22:05 UTC, dylans commented on README.md
> +Allows subtitution of the default widget stub with a custom widget stub which allows additinal stub/mock/spy functionality in
subtitution -> substitution

2017-04-13 22:05 UTC, dylans commented on README.md
> +Allows subtitution of the default widget stub with a custom widget stub which allows additinal stub/mock/spy functionality in
additinal -> additional

2017-04-13 22:05 UTC, dylans commented on README.md
> +By default, any sub-widgets (virtual DOM returned from `w()` or a `WNode`) are subtituted with a special class of widget called
Should probably be consistent in calling things sub widget, sub-widget or SubWidget throughout the docs

2017-04-13 22:05 UTC, dylans commented on README.md
> +By default, any sub-widgets (virtual DOM returned from `w()` or a `WNode`) are subtituted with a special class of widget called
subtituted -> substituted

2017-04-13 22:05 UTC, dylans commented on README.md
> +inject something into the sub widget on render, then you may need to make some assertions against this.
against this... be explicit on what this is

2017-04-13 22:05 UTC, dylans commented on README.md
> +In most cases this should be sufficient for testing the harnessed widget, but if the enclosing harnessed widget is going to
this should -> be explicit on what this is

2017-04-13 22:05 UTC, dylans commented on README.md
> +Therefore the `harness` module has a few exports to facilitate this as well as an API for specifying the mapping:
this... be explicit on what this is

2017-04-13 22:05 UTC, dylans commented on README.md
> +- `StubWidgetMapValue` - A type that represents acceptable stub widget constructors.  Itended to be used when passing the map as an iterable.
Itended -> Intended

2017-04-13 22:05 UTC, dylans commented on README.md
> +The easiest way to provide mappings of widget to stub is to use the `.map()` method on the harness instance.  For example, assuming you
"mappings of widget to stub" singular/plural mismatch?

2017-04-13 22:05 UTC, dylans commented on README.md
> +The `.map()` method returns a `Handle` which can be used to remove a mapped subtitution once added, which will cause the next render to
subtitution -> substitution

2017-04-13 22:05 UTC, dylans commented on README.md
> +In addition, the map of substituions can be passed as an iterable as the second argument to the `harness()` function.  This is inteded
substituions -> so many creative ways to spell substitution :)

2017-04-13 22:05 UTC, dylans commented on README.md
> +In addition, the map of substituions can be passed as an iterable as the second argument to the `harness()` function.  This is inteded
inteded -> intended

2017-04-13 22:05 UTC, dylans commented on README.md
> +to make it easier to _reuse_ maps of substituions in multple tests.  For example:
substituions ->  substitutions

2017-04-13 22:05 UTC, dylans commented on README.md
> +to make it easier to _reuse_ maps of substituions in multple tests.  For example:
multple -> multiple

2017-04-13 22:05 UTC, dylans commented on src/harness.ts
> + * A map of widget constructors and the subtitute stubs
subtitute -> substitute

2017-04-18 13:07 UTC, kitsonk commented
The use case for this was obviated by other ways... Closing this for now.  We can re-open if there is a valid use case, but it is likely functionality without a use ATM.

2017-04-18 13:07 UTC, closed without merging